language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install -f libboost-dev libboost-serialization-dev libboost-filesystem-dev libboost-system-dev libboost-test-dev libboost-thread-dev
  - sudo apt-get install -f mongodb-dev || true
before_script:
  - git submodule update --init --recursive
  - cd test
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib
script:
  - ./waf configure install
  - ./bin/main --gtest_filter=-JSONBuiltin/15.BuiltinTypes

# vim: et ts=2 sw=2
